language: csharp
solution: AlgebraSystem.sln
mono: latest
dotnet: 3.1

jobs:
  include:
    - dotnet: 3.1
      mono: latest

install:
 - dotnet restore
 - nuget restore

script:
 - dotnet build
 - dotnet test AlgebraSystem.Test/AlgebraSystem.Test.csproj